import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="stylesheet" href="/fox-pet.css" />
      </head>
      <body className="min-h-full flex flex-col">
        {children}
        {/* 狐狸宠物容器 */}
        <div id="fox-pet-container"></div>
        <script src="/fox-pet.js" />
        <script>
          {`
            document.addEventListener('DOMContentLoaded', function() {
              if (typeof initFoxPet === 'function') {
                initFoxPet();
              }
            });
          `}
        </script>
      </body>
    </html>
  );
}
